/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContentPolicyRouteImport } from './routes/content-policy'
import { Route as HowToHelpRouteImport } from './routes/how-to-help'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SubmitCaseRouteImport } from './routes/submit-case'
import { Route as SubmitInformationRouteImport } from './routes/submit-information'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as VerificationPolicyRouteImport } from './routes/verification-policy'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditLogRouteImport } from './routes/admin.audit-log'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSourcesRouteImport } from './routes/admin.sources'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as AdminUpdatesRouteImport } from './routes/admin.updates'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CasesSlugRouteImport } from './routes/cases.$slug'
import { Route as AdminCasesIndexRouteImport } from './routes/admin.cases.index'
import { Route as AdminCasesIdRouteImport } from './routes/admin.cases.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentPolicyRoute = ContentPolicyRouteImport.update({
  id: '/content-policy',
  path: '/content-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToHelpRoute = HowToHelpRouteImport.update({
  id: '/how-to-help',
  path: '/how-to-help',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitCaseRoute = SubmitCaseRouteImport.update({
  id: '/submit-case',
  path: '/submit-case',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitInformationRoute = SubmitInformationRouteImport.update({
  id: '/submit-information',
  path: '/submit-information',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationPolicyRoute = VerificationPolicyRouteImport.update({
  id: '/verification-policy',
  path: '/verification-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUpdatesRoute = AdminUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesSlugRoute = CasesSlugRouteImport.update({
  id: '/cases/$slug',
  path: '/cases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCasesIndexRoute = AdminCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCasesIdRoute = AdminCasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/content-policy': typeof ContentPolicyRoute
  '/how-to-help': typeof HowToHelpRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/submit-case': typeof SubmitCaseRoute
  '/submit-information': typeof SubmitInformationRoute
  '/terms': typeof TermsRoute
  '/updates': typeof UpdatesRoute
  '/verification-policy': typeof VerificationPolicyRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/updates': typeof AdminUpdatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/admin/cases/$id': typeof AdminCasesIdRoute
  '/admin/cases/': typeof AdminCasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/content-policy': typeof ContentPolicyRoute
  '/how-to-help': typeof HowToHelpRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/submit-case': typeof SubmitCaseRoute
  '/submit-information': typeof SubmitInformationRoute
  '/terms': typeof TermsRoute
  '/updates': typeof UpdatesRoute
  '/verification-policy': typeof VerificationPolicyRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/updates': typeof AdminUpdatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/cases': typeof CasesIndexRoute
  '/admin/cases/$id': typeof AdminCasesIdRoute
  '/admin/cases': typeof AdminCasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/content-policy': typeof ContentPolicyRoute
  '/how-to-help': typeof HowToHelpRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/submit-case': typeof SubmitCaseRoute
  '/submit-information': typeof SubmitInformationRoute
  '/terms': typeof TermsRoute
  '/updates': typeof UpdatesRoute
  '/verification-policy': typeof VerificationPolicyRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/updates': typeof AdminUpdatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/admin/cases/$id': typeof AdminCasesIdRoute
  '/admin/cases/': typeof AdminCasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/content-policy'
    | '/how-to-help'
    | '/privacy'
    | '/search'
    | '/submit-case'
    | '/submit-information'
    | '/terms'
    | '/updates'
    | '/verification-policy'
    | '/admin/audit-log'
    | '/admin/documents'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/sources'
    | '/admin/submissions'
    | '/admin/updates'
    | '/admin/users'
    | '/cases/$slug'
    | '/admin/'
    | '/cases/'
    | '/admin/cases/$id'
    | '/admin/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/content-policy'
    | '/how-to-help'
    | '/privacy'
    | '/search'
    | '/submit-case'
    | '/submit-information'
    | '/terms'
    | '/updates'
    | '/verification-policy'
    | '/admin/audit-log'
    | '/admin/documents'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/sources'
    | '/admin/submissions'
    | '/admin/updates'
    | '/admin/users'
    | '/cases/$slug'
    | '/admin'
    | '/cases'
    | '/admin/cases/$id'
    | '/admin/cases'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/content-policy'
    | '/how-to-help'
    | '/privacy'
    | '/search'
    | '/submit-case'
    | '/submit-information'
    | '/terms'
    | '/updates'
    | '/verification-policy'
    | '/admin/audit-log'
    | '/admin/documents'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/sources'
    | '/admin/submissions'
    | '/admin/updates'
    | '/admin/users'
    | '/cases/$slug'
    | '/admin/'
    | '/cases/'
    | '/admin/cases/$id'
    | '/admin/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ContentPolicyRoute: typeof ContentPolicyRoute
  HowToHelpRoute: typeof HowToHelpRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SubmitCaseRoute: typeof SubmitCaseRoute
  SubmitInformationRoute: typeof SubmitInformationRoute
  TermsRoute: typeof TermsRoute
  UpdatesRoute: typeof UpdatesRoute
  VerificationPolicyRoute: typeof VerificationPolicyRoute
  CasesSlugRoute: typeof CasesSlugRoute
  CasesIndexRoute: typeof CasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-policy': {
      id: '/content-policy'
      path: '/content-policy'
      fullPath: '/content-policy'
      preLoaderRoute: typeof ContentPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-help': {
      id: '/how-to-help'
      path: '/how-to-help'
      fullPath: '/how-to-help'
      preLoaderRoute: typeof HowToHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-case': {
      id: '/submit-case'
      path: '/submit-case'
      fullPath: '/submit-case'
      preLoaderRoute: typeof SubmitCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-information': {
      id: '/submit-information'
      path: '/submit-information'
      fullPath: '/submit-information'
      preLoaderRoute: typeof SubmitInformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification-policy': {
      id: '/verification-policy'
      path: '/verification-policy'
      fullPath: '/verification-policy'
      preLoaderRoute: typeof VerificationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sources': {
      id: '/admin/sources'
      path: '/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/updates': {
      id: '/admin/updates'
      path: '/updates'
      fullPath: '/admin/updates'
      preLoaderRoute: typeof AdminUpdatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$slug': {
      id: '/cases/$slug'
      path: '/cases/$slug'
      fullPath: '/cases/$slug'
      preLoaderRoute: typeof CasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cases/': {
      id: '/admin/cases/'
      path: '/cases'
      fullPath: '/admin/cases/'
      preLoaderRoute: typeof AdminCasesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cases/$id': {
      id: '/admin/cases/$id'
      path: '/cases/$id'
      fullPath: '/admin/cases/$id'
      preLoaderRoute: typeof AdminCasesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSourcesRoute: typeof AdminSourcesRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminUpdatesRoute: typeof AdminUpdatesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCasesIdRoute: typeof AdminCasesIdRoute
  AdminCasesIndexRoute: typeof AdminCasesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSourcesRoute: AdminSourcesRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminUpdatesRoute: AdminUpdatesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCasesIdRoute: AdminCasesIdRoute,
  AdminCasesIndexRoute: AdminCasesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ContentPolicyRoute: ContentPolicyRoute,
  HowToHelpRoute: HowToHelpRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SubmitCaseRoute: SubmitCaseRoute,
  SubmitInformationRoute: SubmitInformationRoute,
  TermsRoute: TermsRoute,
  UpdatesRoute: UpdatesRoute,
  VerificationPolicyRoute: VerificationPolicyRoute,
  CasesSlugRoute: CasesSlugRoute,
  CasesIndexRoute: CasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
